### ISSUE TITLE
As a user I would like to browse books.

### ISSUE THREAD

**Issue by patdel0** [fac25/week6-J-A-M-P#1]
- [x] #6
- [x] #5
- [x] #7

**Comment by flare-s** [comment]
![Book Deals   Offers _ Multibuy and Sale on Best Seller Books   Novels _ Free Delivery on Orders Over](https://user-images.githubusercontent.com/61504375/197765669-09daab75-6e15-49d7-86b8-8e0e81b7f21f.png)

**Comment by modanova** [comment]
DB SQLite table columns:
- id
- title
- author
- genre
- price
- description
