### ISSUE TITLE
 As a user I would like to have more details about a specific book.

### ISSUE THREAD

**Issue by patdel0** [fac25/week6-J-A-M-P#2]
- [x] #14
- [x] #10
- [x] TItle
- [x] Author
- [x] Description
- [x] Image
- [x] Genre

**Comment by flare-s** [comment]
![Afternoons With The Blinds Drawn _ Books _ Free shipping over £20 _ HMV Store](https://user-images.githubusercontent.com/61504375/197765906-2c629945-b2af-4659-b278-6fa124dbeaf5.png)
